### PR TITLE
updated inflections

### PR DESCRIPTION
**Pull request by longrunningprocess**
# Sampling of additions with this release

Adjectives: arrogant, awesome
Adverbs:  powerfully, securely
Nouns: Agrippa, Ananias, ant
Verbs: depend, grasp

### CODE REVIEW

**Review by craigp-atw — CHANGES_REQUESTED** [review]
Awesome, that's a lot of new words!

In `database/inflections/to_csv.mjs`, you can now remove 'prophesy' and 'result' from the `add_missing_words()` function.

**Comment by longrunningprocess** [comment]
> Awesome, that's a lot of new words!
> 
> In `database/inflections/to_csv.mjs`, you can now remove 'prophesy' and 'result' from the `add_missing_words()` function.

Great catch!  [PR feedback](https://github.com/presciencelabs/tabitha-editor/pull/121/commits/48ba7d90417337652657f0b8f2138abe03c357a5)

**Comment by craigp-atw** [comment]
> Great catch! [PR feedback](https://github.com/presciencelabs/tabitha-editor/pull/121/commits/48ba7d90417337652657f0b8f2138abe03c357a5)

I would re-run that script again to remove the duplicate entries from the output csv files. Are there multiple entries within the database? We might also want to re-import the data.

**Comment by longrunningprocess** [comment]
> > Great catch! [PR feedback](https://github.com/presciencelabs/tabitha-editor/pull/121/commits/48ba7d90417337652657f0b8f2138abe03c357a5)
> 
> I would re-run that script again to remove the duplicate entries from the output csv files. Are there multiple entries within the database? We might also want to re-import the data.

yep, good call, I've done that now.

**Review by craigp-atw — APPROVED** [review]

**Pull request merged**
